version: "3.9"

services:
  3LangBot:
    build: .
    container_name: 3LangBot
    restart: always
    env_file:
      - .env
    volumes:
      - ./credentials.json:/app/credentials.json
    command: python bot.py
